apiVersion: 1

datasources:
  - name: influxdb
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    uid: influxdb
    jsonData:
      version: Flux
      organization: pubg-org
      defaultBucket: pubg-metrics
      tlsSkipVerify: true
    secureJsonData:
      token: my-super-secret-auth-token
    isDefault: true